Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  
  config.vm.network "private_network", ip: "192.168.56.10"
  
  config.vm.hostname = "servidor-nginx"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end
end